url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/fullstack-python" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-paginate

markdown: kramdown
highlighter: rouge
linenos: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

paginate: 5
paginate_path: /page:num/
  