url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/fullstack-python" # the subpath of your site, e.g. /blog
title: "fullstack python" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-paginate
  - jekyll-tabs

markdown: kramdown
highlighter: rouge
linenos: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /:categories/:title:output_ext


collections:
  software:
    output: true
  desafios:
    output: true

paginate: 5
paginate_path: /page:num/
